name: CI/CD Pipeline to deploy your application

on:
  push:
    branchs:
      - main

jobs:
  deploy:
    name: deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-actions@v1.0.0
        with:
          host:
