name: Deploy a Nodejs App to Ec2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Using Machine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/ec2-ci-cd
            git pull origin main
            npm install
            pm2 restart server.js || pm2 start server.js
